from reportlab.lib.pagesizes import letter
from reportlab.pdfgen import canvas
from reportlab.lib.utils import ImageReader
import os

class PDFGenerator:
    def __init__(self):
        self.output_dir = "generated_books"
        os.makedirs(self.output_dir, exist_ok=True)

    async def create_book_pdf(self, pages: list, filename: str) -> str:
        """
        Generates a PDF from a list of pages.
        Each page in the list is a dict with 'text' and optional 'image_path'.
        """
        output_path = os.path.join(self.output_dir, filename)
        c = canvas.Canvas(output_path, pagesize=letter)
        width, height = letter

        # Title Page
        c.setFont("Helvetica-Bold", 24)
        c.drawCentredString(width / 2, height / 2 + 50, "My Islamic Children's Book")
        c.setFont("Helvetica", 14)
        c.drawCentredString(width / 2, height / 2, "Generated by ICBG")
        c.showPage()

        # Content Pages
        for i, page in enumerate(pages):
            # Text
            text = page.get("text", "")
            c.setFont("Helvetica", 12)
            text_object = c.beginText(50, height - 50)
            for line in text.split('\n'):
                text_object.textLine(line)
            c.drawText(text_object)

            # Image Placeholder (or actual image if we had one)
            # c.rect(50, height - 400, 500, 300)
            c.drawString(50, height - 420, f"[Image for Page {i+1}]")

            c.showPage()

        c.save()
        return output_path
