from reportlab.lib.pagesizes import letter
from reportlab.pdfgen import canvas
from reportlab.lib.utils import ImageReader
import os

class PDFGenerator:
    def __init__(self):
        self.output_dir = "generated_books"
        os.makedirs(self.output_dir, exist_ok=True)

    async def create_book_pdf(self, pages: list, filename: str, title: str = "My Islamic Children's Book") -> str:
        """
        Generates a PDF from a list of pages.
        Each page in the list is a dict with 'text' and optional 'image_path'.
        """
        output_path = os.path.join(self.output_dir, filename)
        c = canvas.Canvas(output_path, pagesize=letter)
        width, height = letter

        # Title Page
        c.setFont("Helvetica-Bold", 24)
        c.drawCentredString(width / 2, height / 2 + 50, title)
        c.setFont("Helvetica", 14)
        c.drawCentredString(width / 2, height / 2, "Generated by ICBG")
        c.showPage()

        # Content Pages
        for i, page in enumerate(pages):
            # Image (Top Half)
            image_path = page.get("image_path")
            if image_path and os.path.exists(image_path):
                try:
                    # Draw image at the top
                    # Page height is ~792 points (Letter)
                    # Let's place image from y=400 to y=700 (height 300)
                    img_width = 400
                    img_height = 300
                    x = (width - img_width) / 2
                    y = height - 350 # Top margin
                    c.drawImage(image_path, x, y, width=img_width, height=img_height, preserveAspectRatio=True)
                except Exception as e:
                    print(f"Error drawing image {image_path}: {e}")
                    c.drawString(50, height - 200, f"[Error loading image]")
            else:
                # Placeholder
                c.drawString(50, height - 200, f"[Image Placeholder]")

            # Text (Bottom Half)
            text = page.get("text", "")
            c.setFont("Helvetica", 18) # Larger font for children
            
            # Start text below the image area with some padding
            text_y_start = height - 400 
            line_height = 24 # More spacing
            
            text_object = c.beginText(50, text_y_start)
            text_object.setLeading(line_height)
            
            # Smart wrapping using textwrap
            import textwrap
            # Calculate chars per line based on font size and page width
            # Letter width = 612. Margins = 50+50=100. Usable = 512.
            # Approx char width for 18pt Helvetica is ~9-10pts. 512/9 = ~56 chars.
            max_chars = 55 
            
            wrapped_lines = []
            for paragraph in text.split('\n'):
                wrapped_lines.extend(textwrap.wrap(paragraph, width=max_chars))
            
            # Center vertically in the available space if text is short
            # Available height = text_y_start - bottom_margin (50) = ~350
            total_text_height = len(wrapped_lines) * line_height
            available_height = text_y_start - 50
            
            if total_text_height < available_height:
                # Center it
                offset = (available_height - total_text_height) / 2
                text_object.setTextOrigin(50, text_y_start - offset)
            
            for line in wrapped_lines:
                text_object.textLine(line)
            c.drawText(text_object)

            c.showPage()

        c.save()
        return output_path
